name: Merge and save AppMap archives from a matrix job
inputs:
  directory:
    description: Command working directory.
  archive-count:
    description: Number of archive files to merge.
    required: true
  revision:
    description: |
      Revision (commit SHA) to name the AppMap archive with. The default is the GITHUB_SHA.
      Note that setting this variable does not change the version of the code that's actually checked
      out and run - it just specifies what commit the built archive is associated with. Using this variable,
      you can make a branch off an existing commit, build an archive on that branch, and assign it to the
      original commit that you branched from, thereby adding an AppMap archive for a historical revision.
      In a pull request action, use `github.event.pull_request.head.sha`.
  verbose:
    description: Enable verbose logging.
    default: false
runs:
  using: 'node16'
  main: '../dist/merge/index.js'
