name: Build and save an AppMap archive
inputs:
  directory:
    description: Command working directory.
  archive-id:
    description: |
      0-based numerical id of a matrix job. This id is used to store the AppMap archive in the action cache.
      Once the matrix jobs complete, the `merge` action can be used to merge the archives into a single archive,
      and then save it as an artifact. If `archive-id` is set, the archive is saved to the cache. Otherwise,
      it's uploadd to the artifact store. For a non-matrix job, `archive-id` should not be used.
    type: number
  revision:
    description: |
      Revision (commit SHA) to name the AppMap archive with. The default is the GITHUB_SHA.
      Note that setting this variable does not change the version of the code that's actually checked
      out and run - it just specifies what commit the built archive is associated with. Using this variable,
      you can make a branch off an existing commit, build an archive on that branch, and assign it to the
      original commit that you branched from, thereby adding an AppMap archive for a historical revision.
      In a pull request action, use `github.event.pull_request.head.sha`.
  verbose:
    description: Enable verbose logging.
    default: false
runs:
  using: 'node16'
  main: 'dist/archive/index.js'
