name: Archive AppMaps on PR merge

on:
  pull_request:
    types:
      - closed
  schedule:
    # Keep the artifact up to date, as it will expire after 90 days.
    - cron: 1 1 1 * *

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  appmap_archive_main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout step
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Install and configure AppMap tools
        uses: getappmap/install-appmap-action@v1-pre.6
        id: install-appmap
        with:
          verbose: true
      - name: Build AppMaps
        run: yarn appmap
      - name: Archive AppMaps
        uses: ./
        id: archive-appmap
        with:
          verbose: true
